# Generated by Django 3.2.9 on 2021-12-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_buymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='buymodel',
            name='user',
        ),
    ]
