# Generated by Django 3.2.9 on 2021-12-05 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211204_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymodel',
            name='interact_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ReturnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('interact_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.goods')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
