# Generated by Django 3.2.9 on 2021-12-05 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211205_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnmodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='returnmodel',
            name='good',
        ),
        migrations.AddField(
            model_name='returnmodel',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.buymodel'),
        ),
    ]
